world_frame_id: "world"
fixed_anchors: [DW4806, DW009A, DW47FC]
n_networks : 2
network1: 
  network_id: "0x5B1C"
  tag_id: "DW482E"
  n_anchors: 5
  anchor0_id: "DW4984"
  anchor1_id: "DW4806" 
  anchor2_id: "DW4814"
  anchor3_id: "DW43EB"
  anchor4_id: "DW1632"
  anchor0_coordinates: [3.13, 3.26, 0.00] #DW4984
  anchor1_coordinates: [4.53, 3.26, 0.00] #DW4806
  anchor2_coordinates: [4.00, 1.00, 0.00] #DW4814
  anchor3_coordinates: [3.00, 0.00, 2.17] #DW43EB
  anchor4_coordinates: [4.00, 0.00, 2.00] #DW1632
  gt:
    anchor0_coordinates: [2.13, 3.26, 0.00] #DW4984
    anchor1_coordinates: [4.53, 3.26, 0.00] #DW4806
    anchor2_coordinates: [3.33, 2.06, 0.00] #DW4814
    anchor3_coordinates: [1.97, 0.00, 2.17] #DW43EB
    anchor4_coordinates: [4.46, 0.00, 2.17] #DW1632

network0: 
  network_id: "0x11A7"
  tag_id: "DW02D6"
  n_anchors: 5
  anchor0_id: "DW009A"
  anchor1_id: "DW2D9C"
  anchor2_id: "DW4848"
  anchor3_id: "DW47FC"
  anchor4_id: "DW0038"
  anchor0_coordinates: [0.93, 3.26, 0.00] #DW009A
  anchor1_coordinates: [4.33, 3.26, 0.00] #DW2D9C
  anchor2_coordinates: [3.13, 2.06, 0.00] #DW4848
  anchor3_coordinates: [0.40, 0.00, 2.17] #DW47FC
  anchor4_coordinates: [3.00, 0.00, 2.17] #DW0038
  gt:
    anchor0_coordinates: [0.93, 3.26, 0.00] #DW009A
    anchor1_coordinates: [3.33, 3.26, 0.00] #DW2D9C
    anchor2_coordinates: [2.13, 2.06, 0.00] #DW4848
    anchor3_coordinates: [0.40, 0.00, 2.17] #DW47FC
    anchor4_coordinates: [2.90, 0.00, 2.17] #DW0038