world_frame_id: "world"
n_networks : 1
network1: 
  network_id: "0x5B1C"
  tag_id: "DW482E"
  n_anchors: 5
  anchor0_id: "DW4984"
  anchor1_id: "DW4806" 
  anchor2_id: "DW4814"
  anchor3_id: "DW43EB"
  anchor4_id: "DW1632"
  anchor0_coordinates: [0.93, 3.67, 0.00] #DW4984
  anchor1_coordinates: [0.93, 2.07, 0.00] #DW4806
  anchor2_coordinates: [0.93, 0.87, 0.00] #DW4814
  anchor3_coordinates: [8.13, 3.67, 0.00] #DW43EB
  anchor4_coordinates: [8.13, 2.07, 0.00] #DW1632

network0: 
  network_id: "0x11A7"
  tag_id: "DW02D6"
  n_anchors: 5
  anchor0_id: "DW009A"
  anchor1_id: "DW2D9C"
  anchor2_id: "DW4848"
  anchor3_id: "DW47FC"
  anchor4_id: "DW0038"
  anchor0_coordinates: [0.00, 0.00, 0.00] #DW009A
  anchor1_coordinates: [0.00, 2.00, 0.00] #DW2D9C
  anchor2_coordinates: [1.00, 1.00, 0.00] #DW4848
  anchor3_coordinates: [2.00, 0.00, 0.00] #DW47FC
  anchor4_coordinates: [2.00, 2.00, 0.00] #DW0038