serial_port: "/dev/ttyACM0"
tag_device_id: "DW02D6"
use_network: False
network: "network0"
verbose: True
num_anchors: 3
algorithm: 0
dimension: 0
height: 0
frequency: 0
world_frame_id: "world"
tag_frame_id: "tag_frame"

